### ISSUE TITLE
[BUG] Persistent PVC Handling

### ISSUE THREAD

**Issue by HaleyACS** [fastlorenzo/helm-charts-1#32]
**Describe the bug**
All the persistent settings are not reflected when deploying.
Existing PVC is always deleted, even though the system is supposed to use an existing PVC.

**Environment**
k3s on ubuntu server 22.04
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8+k3s1", GitCommit:"5d0a12a6168bf2140216913ea9e5df6f81a26ec6", GitTreeState:"clean", BuildDate:"2021-06-21T20:44:53Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8+k3s1", GitCommit:"5d0a12a6168bf2140216913ea9e5df6f81a26ec6", GitTreeState:"clean", BuildDate:"2021-06-21T20:44:53Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.18.8"}
```

**Additional context**
```
persistence:
  single_pvc: true
  #size: 100Gi
  #hostPath: "/data/mailu"
  existingClaim: "mailu-storage"
  #type: ""
```
When adding a single PVC and telling the system to use an existing Claim - current setup tries to modify the claim resulting in an error message:
```
Warning: resource secrets/mailu-certificates is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
secret/mailu-certificates configured
The PersistentVolumeClaim "mailu-storage" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
        AccessModes:      {"ReadWriteOnce"},
        Selector:         nil,
        Resources:        {Requests: {s"storage": {i: {...}, s: "100Gi", Format: "BinarySI"}}},
-       VolumeName:       "",
+       VolumeName:       "mailu-storage",
        StorageClassName: &"local-path",
        VolumeMode:       &"Filesystem",
        DataSource:       nil,
  }
```

If an existing pvc claim is to be used, and single_pvc is to be used, then no pv/pvc operation should be done.

**Comment by fastlorenzo** [comment]
It looks like the `volumeName` attribute is only set if `persistence.hostPath` is set.

https://github.com/fastlorenzo/helm-charts-1/blob/8324f142210a2caac3fa2ec68b81433fab65929f/mailu/templates/pvc.yaml#L32-L34

If I understand your setup (using the PV/PVC config you provided in #33 , the PV from https://github.com/fastlorenzo/helm-charts-1/blob/master/mailu/templates/pv-hostpath.yaml shouldn't be created as you use an `existingClaim`.

**Comment by fastlorenzo** [comment]
At second look, it's even more simpler than that. Because you use an existing claim, the PV and PVC should not be created at all by the chart.

I'll make a fix in https://github.com/fastlorenzo/helm-charts-1/blob/8324f142210a2caac3fa2ec68b81433fab65929f/mailu/templates/pvc.yaml#L2 and https://github.com/fastlorenzo/helm-charts-1/blob/8324f142210a2caac3fa2ec68b81433fab65929f/mailu/templates/pv-hostpath.yaml#L2 to check for it

**Comment by HaleyACS** [comment]
I'd re-open it.
When the pvc claim is supposed to exist,t he pv and pvc are created by the user upfront.
In the current implementation, when deleting the helm chart (yaml files), the pv is left the pvc itself is removed.
It should not touch the pv nor the pvc - on deploying or decommissioning the mailu server IMHO.
