### ISSUE TITLE
[BUG] TLS section in ingress is not set if just ingress.tls=true is configured

### ISSUE THREAD

**Issue by micw** [fastlorenzo/helm-charts-1#37]
The condition for TLS is:

```
 {{- if and .Values.ingress.tls (or (include "common.ingress.certManagerRequest" ( dict "annotations" .Values.ingress.annotations )) .Values.ingress.secrets .Values.ingress.selfSigned) }}
```

Breakdown:

```
ingress.tls AND (ingress.annotations OR ingress.selfSigned)
```

That means without annotations, no tls section is created. IMO it should always be created if `ingress.tls=true` since the certificate could be added in a different way and/or without any annotations.

**Comment by fastlorenzo** [comment]
Actually, the full check is 
```yaml
  {{- if or (and .Values.ingress.tls (or (include "common.ingress.certManagerRequest" ( dict "annotations" .Values.ingress.annotations )) .Values.ingress.selfSigned .Values.ingress.secrets )) .Values.ingress.extraTls }}
```

which would be:
```
ingres.tls=true AND (ingress.annotations OR ingress.secrets OR ingress.selfSigned)
OR
ingress.extraTls
```

If you don't use `ingress.annotations` or `ingress.secrets` or `ingress.selfSigned` and want to use TLS generated in another way, you should provide the information via `ingress.extraTls`.

Example:
```yaml
ingress:
  extraTls:
    - hosts:
        - mailu.local
      secretName: mailu-local-tls
```

I don't see where it is posing an issue here, maybe you didn't pass the value via `ingress.extraTls` ?

It'll be helpful if you could provide more information to reproduce.

**Comment by micw** [comment]
I just did not understand why not just ingress.tls=true is sufficient. From the paramater naming would assume that this enabled the ingress tls part.

**Comment by fastlorenzo** [comment]
But then how do you specify which certificate to use if you generate it outside of the chart? 

At the moment you have 4 ways of doing it:
1. Generate it using cert-manager through the `annotations` option
2. Provide the PEM encoded values via the `secrets` option
3. Configure it using an existing secret containing the certificates via the `extraTls` option
4. Generate a self-signed certificate using `selfSigned` option

**Comment by fastlorenzo** [comment]
Now that I read my comment again, you have a 5th option: use the `existingSecret` option, which is not tackled in the ingres config. Maybe that one needs to be added in the check as well (if this is the one you are using).
It is less granular than the `extraTls`, which allows to define different certificates per host, but an easy configuration option maybe.
