### ISSUE TITLE
[BUG] - Issue with upgrading to betas 23 and 24.

### ISSUE THREAD

**Issue by smolinari** [fastlorenzo/helm-charts-1#42]
Hi,

When I try to upgrade the chart with betas 23 or 24, I get the following error:

![image](https://user-images.githubusercontent.com/3314957/204000655-0c850477-6e85-46e2-b35e-263cebb0b31b.png)

**Environment**
 - k3s v1.24.6 (3 master, 4 worker nodes)
 - Helm v3.9.4
 - Ubuntu 22.04

Using beta 22 works. 

Scott

**Comment by fastlorenzo** [comment]
can you try deleting the `mailu-clamav` statefulset manually then applying the upgrade?

**Comment by smolinari** [comment]
That worked. Thanks! I've successfully updated to beta24. Beta25 failed, because values are missing for the new `mailu-webmail` pod? Seems roundcube was replace (in terminology?) with with webmail? 

Is just swapping out the roundcube section for the new webmail section enough? 

Scott

**Comment by fastlorenzo** [comment]
yes, swapping `roundcube` with `webmail` in values should be enough, closing this one then ;)
