### ISSUE TITLE
[BUG] - Clamv StatefulSet must be deleted to upgrade

### ISSUE THREAD

**Issue by smolinari** [fastlorenzo/helm-charts-1#52]
Hi,

When upgrading to beta.27, I had to delete the clamv StatefulSet in order for the upgrade to work. 

**Environment**
 - k3s v1.24.6 (3 master, 4 worker nodes)
 - Helm v3.9.4
 - Ubuntu 22.04

Scott

**Comment by fastlorenzo** [comment]
After further investigation, it seems to be inherent to the way some StatefulSet parameters are immutable.
If the chart upgrade changes those parameters, we need to delete and recreate the StatefulSet.
I didn't find any automated way to doing so when upgrading, so the only workaround I see is to manually delete the StatefulSet and then upgrade the chart.
